const slug=new URLSearchParams(location.search).get('miasto');
const city=CITIES.find(item=>item.slug===slug)||CITIES[0];
document.title=`${city.name} — Studenci Polska`;
const universityGroups=UNIVERSITY_GROUPS[city.slug]||[];
const universitySection=universityGroups.length?`<section class="universities-section"><div class="universities-head"><div><p class="overline blue">GRUPY UCZELNIANE</p><h2>Znajdź swoich<br><em>z uczelni.</em></h2></div><p>${universityGroups.length} grup dla studentów uczelni w mieście ${city.name}. Wybierz swoją szkołę i dołącz bezpośrednio na Facebooku.</p></div><div class="universities-grid">${universityGroups.map((group,index)=>`<a class="university-card" href="${group[2]}" target="_blank" rel="noopener noreferrer"><span class="university-number">${String(index+1).padStart(2,'0')}</span><strong>${group[0]}</strong><p>${group[1]}</p><i>↗</i></a>`).join('')}</div></section>`:'';
const cityEvents=CITY_EVENTS[city.slug]||[];
const eventsSection=cityEvents.length?`<section class="events-section"><div class="events-head"><div><p class="overline blue">NADCHODZĄCE IMPREZY STUDENCKIE</p><h2>Spotkajmy się<br><em>na żywo.</em></h2></div><p>${cityEvents.length} nadchodzących wydarzeń dla studentów w mieście ${city.name}. Kliknij plakat, aby przejść do wydarzenia na Facebooku.</p></div><div class="events-grid real-events">${cityEvents.map((event,index)=>`<a class="event-card" href="${event[2]}" target="_blank" rel="noopener noreferrer"><div class="event-image"><img src="${event[1]}" alt="${event[0]}" loading="lazy"><span>${String(index+1).padStart(2,'0')}</span><i>↗</i></div><p>WYDARZENIE STUDENCKIE</p><h3>${event[0]}</h3><b>Zobacz wydarzenie →</b></a>`).join('')}</div></section>`:`<section class="events-section"><div class="events-head"><div><p class="overline blue">WYDARZENIA W MIEŚCIE</p><h2>Spotkajmy się<br><em>na żywo.</em></h2></div><p>Już wkrótce pojawią się tutaj dedykowane wydarzenia dla studentów w mieście ${city.name}.</p></div><div class="events-grid"><article class="event-placeholder"><div class="event-art"><span>01</span><i>＋</i></div><p>WKRÓTCE</p><h3>Pierwsze wydarzenie</h3><span>Grafika i szczegóły pojawią się niebawem.</span></article><article class="event-placeholder"><div class="event-art alt"><span>02</span><i>＋</i></div><p>WKRÓTCE</p><h3>Kolejne spotkanie</h3><span>To miejsce czeka na dedykowane wydarzenie.</span></article><article class="event-placeholder"><div class="event-art dark"><span>03</span><i>＋</i></div><p>WKRÓTCE</p><h3>Coś specjalnego</h3><span>Obserwuj grupę, żeby niczego nie przegapić.</span></article></div></section>`;
document.getElementById('cityPage').innerHTML=`
<section class="city-hero" style="--city-image:url('${city.image}')"><div class="city-hero-shade"></div><div class="city-hero-copy"><p class="overline">${city.region.toUpperCase()} · MIASTO ${city.number}</p><h1>${city.name}</h1><p>${city.desc}</p><a class="button" href="#dolacz">Dołącz do społeczności <span>↓</span></a></div></section>
<section class="join-section" id="dolacz"><div class="join-copy"><p class="overline">SPOŁECZNOŚĆ ${city.name.toUpperCase()}</p><h2>Poznaj ludzi,<br>zanim zacznie się <em>rok.</em></h2><p>Pytaj o uczelnie i mieszkania, poznaj przyszłych znajomych oraz bądź na bieżąco z tym, co dzieje się w mieście.</p></div><a class="join-button" href="${city.facebook}" target="_blank" rel="noopener noreferrer"><span><small>OFICJALNA GRUPA STUDENCKA 2026</small>Dołącz do grupy — ${city.name}</span><b>↗</b></a></section>
${eventsSection}
${universitySection}
<section class="city-features"><article><span>01</span><h3>Studiowanie</h3><p>Sprawdź ofertę lokalnych uczelni i wybierz środowisko dopasowane do Twojego kierunku.</p></article><article><span>02</span><h3>Codzienność</h3><p>Pomyśl o dojazdach, mieszkaniu i miejscach, w których naprawdę będziesz spędzać czas.</p></article><article><span>03</span><h3>Po zajęciach</h3><p>Poznaj kulturę, naturę i społeczność, które budują unikalny klimat miasta.</p></article></section>
<section class="next-city"><p>NASTĘPNE MIASTO</p><a href="city.html?miasto=${CITIES[(CITIES.indexOf(city)+1)%CITIES.length].slug}">${CITIES[(CITIES.indexOf(city)+1)%CITIES.length].name} <span>→</span></a></section>`;
