export const THEME_GROUPS=[
  {slug:'biznes',tag:'BIZNES I ROZWÓJ',title:'Biznes po studencku',description:'Społeczność wymiany doświadczeń, pomysłów i wsparcia dla studentów, którzy chcą rozwijać własne projekty.',url:'https://www.facebook.com/groups/biznes.studenci',guide:'jak-zaczac-biznes-na-studiach',en:'Student business'},
  {slug:'szkolenia',tag:'WIEDZA I KOMPETENCJE',title:'Szkolenia dla studentów',description:'Informacje o warsztatach, kursach i szkoleniach pomagających zdobywać praktyczne umiejętności poza zajęciami.',url:'https://www.facebook.com/groups/szkoleniastudenckie',guide:'kursy-i-szkolenia-dla-studentow',en:'Courses and workshops'},
  {slug:'ai',tag:'TECHNOLOGIA',title:'Grupa dla pasjonatów AI',description:'Miejsce dla osób zainteresowanych sztuczną inteligencją, narzędziami AI i ich zastosowaniem w nauce oraz biznesie.',url:'https://www.facebook.com/groups/uniwersum.biznesu',guide:'ai-w-nauce-i-pracy-studenta',en:'AI enthusiasts'},
  {slug:'moda',tag:'MODA I SECOND HAND',title:'Studencki targ',description:'Grupa dla fanów mody oraz bezpiecznej sprzedaży, kupowania i wymiany ubrań między studentami.',url:'https://www.facebook.com/groups/studenckitarg',guide:'moda-cyrkularna-i-wymiana-ubran',en:'Student fashion exchange'},
  {slug:'gaming',tag:'GRY I ESPORT',title:'Społeczność Polskich Graczy',description:'Rozmowy o grach, wspólne rozgrywki i poznawanie osób o podobnych zainteresowaniach.',url:'https://www.facebook.com/groups/SpolecznoscGraczy',guide:'jak-poznac-ludzi-na-studiach',en:'Polish gaming community'},
  {slug:'praca-zdalna',tag:'PRACA I ZLECENIA',title:'Zdalna praca dla studenta',description:'Oferty zleceń i pracy zdalnej oraz praktyczne rozmowy o bezpiecznym zdobywaniu pierwszego doświadczenia.',url:'https://www.facebook.com/groups/praca.zdalna.studenci',guide:'jak-znalezc-prace-zdalna-na-studiach',en:'Remote work for students'},
  {slug:'zdrowie',tag:'SPORT I ZDROWIE',title:'Sport, fitness i dieta',description:'Studencka społeczność poświęcona aktywności, zdrowym nawykom, diecie i wzajemnej motywacji.',url:'https://www.facebook.com/groups/zdrowie.studenci',guide:'zdrowie-i-rownowaga-na-studiach',en:'Sport, fitness and wellbeing'},
  {slug:'wyjazdy',tag:'PODRÓŻE',title:'Studenckie wyjazdy',description:'Inspiracje, ekipy i praktyczne informacje dla studentów planujących wspólne, rozsądne cenowo podróże.',url:'https://www.facebook.com/groups/studenckie.wyjazdyy',guide:'tanie-wyjazdy-studenckie',en:'Student trips'}
];
